# python3 main.py --datasource omniglot --img-size 28 --img-size 28 --gray-img --ml-type maml --no-google-cloud --logdir /media/n10/Data/TOW --first-order --network-architecture CNN --baseline uniform --baseline exploration --baseline exploitation --no-batchnorm --no-strided --vectorized --num-ways 5 --k-shot 1 --v-shot 15 --beta-u 10 --inner-lr 0.1 --meta-lr 1e-4 --minibatch 10 --num-ilqr-iters 2 --num-time-steps 5 --num-minibatches-print 100 --num-episodes-per-epoch 1000 --num-epochs 100 --resume-epoch 0 --train

# python3 -W ignore main.py --experiment-name miniImageNet --datasource miniImageNet --img-size 84 --img-size 84 --color-img --ml-type maml --no-google-cloud --logdir /home/n10/TOW --first-order --network-architecture CNN --baseline uniform --baseline exploration --baseline exploitation --no-batchnorm --no-strided --vectorized --num-ways 5 --k-shot 1 --v-shot 15 --beta-u 10 --inner-lr 0.01 --meta-lr 1e-4 --minibatch 5 --num-ilqr-iters 2 --num-time-steps 10 --num-workers 4 --dropout-prob 0.75 --jacobian-step 40 --num-minibatches-print 100 --num-episodes-per-epoch 1000 --num-epochs 100 --resume-epoch 0 --train

# python3 -W ignore main.py --experiment-name miniImageNet --datasource miniImageNet --img-size 84 --img-size 84 --color-img --ml-type maml --no-google-cloud --logdir /home/n10/TOW --first-order --network-architecture ResNet10 --baseline uniform --baseline exploration --baseline exploitation --no-batchnorm --no-strided --vectorized --num-ways 5 --k-shot 1 --v-shot 15 --beta-u 10 --inner-lr 0.01 --meta-lr 1e-4 --minibatch 5 --num-ilqr-iters 2 --num-time-steps 10 --num-workers 4 --dropout-prob 0.75 --jacobian-step 40 --num-minibatches-print 100 --num-episodes-per-epoch 1000 --num-epochs 100 --resume-epoch 0 --train

# python3 -W ignore main.py --experiment-name mini-ImageNet --datasource miniImageNet --img-size 84 --img-size 84 --ml-type maml --no-google-cloud --logdir . --first-order --network-architecture CNN --baseline uniform --baseline exploration --baseline exploitation --no-batchnorm --no-strided --vectorized --num-ways 5 --k-shot 0 --k-shot-max 30 --v-shot 15 --beta-u 10 --inner-lr 0.01 --meta-lr 1e-4 --minibatch 5 --num-ilqr-iters 2 --num-time-steps 5 --num-minibatches-print 100 --num-episodes-per-epoch 1000 --num-epochs 30 --resume-epoch 20 --train

# python3 -W ignore main.py --experiment-name mini-ImageNet --datasource mini_ImageNet --ds-folder /home/n10/datasets/ --img-size 84 --img-size 84 --color-img --ml-type maml --logdir . --first-order --network-architecture CNN --baseline uniform --baseline exploration --baseline exploitation --no-batchnorm --no-strided --vectorized --num-ways 5 --k-shot 1 --k-shot-max 1 --v-shot 15 --beta-u 10 --inner-lr 0.01 --meta-lr 1e-4 --minibatch 5 --num-ilqr-iters 2 --num-time-steps 2 --num-workers 4 --dropout-prob 0.75 --jacobian-step 20 --num-minibatches-print 1000 --num-episodes-per-epoch 1000 --num-epochs 51 --resume-epoch 49 --train --run-hash c3bf1c9682ca4fe49c5c975f

# python3 -W ignore main.py --experiment-name mini-ImageNet --datasource mini_ImageNet --ds-folder /home/n10/datasets/ --img-size 84 --img-size 84 --color-img --ml-type maml --logdir . --first-order --network-architecture CNN --baseline uniform --baseline exploration --baseline exploitation --no-batchnorm --no-strided --vectorized --num-ways 5 --k-shot 1 --k-shot-max 1 --v-shot 31 --beta-u 10 --inner-lr 0.1 --meta-lr 1e-4 --minibatch 5 --num-ilqr-iters 2 --num-time-steps 2 --num-workers 4 --dropout-prob 0.75 --jacobian-step 20 --num-minibatches-print 1000 --num-episodes-per-epoch 1000 --num-epochs 100 --resume-epoch 0 --train

python3 -W ignore main.py --experiment-name Omniglot --datasource omniglot --ds-folder /home/n10/datasets/ --img-size 28 --img-size 28 --gray-img --ml-type maml --logdir . --first-order --network-architecture CNN --baseline uniform --baseline exploration --baseline exploitation --no-batchnorm --no-strided --vectorized --num-ways 5 --k-shot 1 --k-shot-max 1 --v-shot 31 --beta-u 10 --inner-lr 0.1 --meta-lr 1e-4 --minibatch 10 --num-ilqr-iters 2 --num-time-steps 2 --num-workers 4 --dropout-prob 0.75 --jacobian-step 20 --num-minibatches-print 1000 --num-episodes-per-epoch 1000 --num-epochs 100 --resume-epoch 0 --train